spring.application.name=PassengerInformationDisplaySystem

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pids_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true